# Builds hydrologic forecast packages or installer (Debian, Python)
#

trigger:
- main
# - testing

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  # use pipeline_src_dir to facilitate testing out of Azure Pipeline
  pipeline_src_dir: $(Build.SourcesDirectory)
  root_out_dir: $(Build.BinariesDirectory)/outputs
  deb_out_dir: $(Build.BinariesDirectory)/outputs/deb
  py_out_dir: $(Build.BinariesDirectory)/outputs/py
  r_out_dir: $(Build.BinariesDirectory)/outputs/r

# to get a custom '$(Build.BuildNumber)', and 'r' is a counter reset to 1 every change of the major/minor versions
# TODO: reference to this technique on the web?
name: '0.2.$(Rev:r)'

# TODO: test stage, or step if it is worth reusing the ubuntu vm (likely)
stages:
- stage: Build
  displayName: Build packages
  jobs:
  - job: Build
    displayName: Build packages
    pool:
      vmImage: ubuntu-latest
    #Cannnot get a service enpoint to work. 
    #https://github.com/MicrosoftDocs/azure-devops-docs/issues/13741
    #container:
    #  image: sfforecastingctnrregistry.azurecr.io/ubuntu-jammy-202310:20231025
    #  endpoint: SfFcastDockerSrvConnection
    # So, just use dockerhub for now.
    container: disparue/ubuntu-jammy-202310:20231025
    steps:
    - checkout: self
    - task: Bash@3
      displayName: 'Where are repos checked out'
      inputs:
        targetType: 'inline'
        script: |
          echo Build.SourcesDirectory=$(Build.SourcesDirectory)
          ls $(Build.SourcesDirectory)
    - task: Bash@3
      displayName: 'Prepare and build checkouts'
      inputs:
        targetType: 'inline'
        script: |
          cd $(Build.SourcesDirectory)/packages
          mkdir -p $(root_out_dir)
          ./checkouts.sh
        failOnStderr: false
        # Tried `true``, but this seemed to lead to failing tasks without obvious real failure. 
        # failOnStderr: true
      env:
        SWIFT_PAT_ENV_VAR: $(SWIFT_PAT) # the recommended way to map to an env variable
        BRANCH_NAME_ENV_VAR: $(Build.SourceBranchName)
    - task: Bash@3
      displayName: 'Build and install debian packages'
      inputs:
        targetType: 'inline'
        script: |
          cd $(Build.SourcesDirectory)/packages
          chmod +x ./build_debian_pkgs.sh
          SRC_ROOT=${HOME}/src
          ROOT_BUILD_DIR=${HOME}/build
          DEB_PKGS_DIR=${ROOT_BUILD_DIR}/deb_pkgs
          DEB_BUILD_ROOT=${HOME}/debbuild
          mkdir -p ${DEB_BUILD_ROOT}
          ./build_debian_pkgs.sh ${DEB_PKGS_DIR} ${SRC_ROOT} ${DEB_BUILD_ROOT}
        failOnStderr: false
        # Tried `true``, but this seemed to lead to failing tasks without obvious real failure. 
        # failOnStderr: true
      env:
        SWIFT_PAT_ENV_VAR: $(SWIFT_PAT) # the recommended way to map to an env variable
        BRANCH_NAME_ENV_VAR: $(Build.SourceBranchName)
    - task: Bash@3
      displayName: 'Run C++ unit tests'
      inputs:
        targetType: 'inline'
        script: |
          chmod +x ./test_native_libraries.sh
          SRC_ROOT=${HOME}/src
          ./test_native_libraries.sh ${SRC_ROOT} 1
        failOnStderr: false
        # Tried `true``, but this seemed to lead to failing tasks without obvious real failure. 
        # failOnStderr: true
      env:
        SWIFT_PAT_ENV_VAR: $(SWIFT_PAT) # the recommended way to map to an env variable
        BRANCH_NAME_ENV_VAR: $(Build.SourceBranchName)
    - task: Bash@3
      displayName: 'Build python packages'
      inputs:
        targetType: 'inline'
        script: |
          chmod +x ./build_python_pkgs.sh
          SRC_ROOT=${HOME}/src
          ROOT_BUILD_DIR=${HOME}/build
          PY_PKGS_DIR=${ROOT_BUILD_DIR}/py_pkgs
          mkdir -p ${PY_PKGS_DIR}
          ./build_python_pkgs.sh ${PY_PKGS_DIR} ${SRC_ROOT}
        failOnStderr: false
        # Tried `true``, but this seemed to lead to failing tasks without obvious real failure. 
        # failOnStderr: true
      env:
        SWIFT_PAT_ENV_VAR: $(SWIFT_PAT) # the recommended way to map to an env variable
        BRANCH_NAME_ENV_VAR: $(Build.SourceBranchName)
    - task: Bash@3
      displayName: 'Build R packages'
      inputs:
        targetType: 'inline'
        script: |
          chmod +x ./build_r_pkgs.sh
          SRC_ROOT=${HOME}/src
          ROOT_BUILD_DIR=${HOME}/build
          R_PKGS_DIR=${ROOT_BUILD_DIR}/r_pkgs
          mkdir -p ${R_PKGS_DIR}
          ./build_r_pkgs.sh ${R_PKGS_DIR} ${SRC_ROOT}
        failOnStderr: false
        # Tried `true``, but this seemed to lead to failing tasks without obvious real failure. 
        # failOnStderr: true
      env:
        SWIFT_PAT_ENV_VAR: $(SWIFT_PAT) # the recommended way to map to an env variable
        BRANCH_NAME_ENV_VAR: $(Build.SourceBranchName)
    - task: Bash@3
      displayName: 'Create small artifact with version'
      inputs:
        targetType: 'inline'
        script: |
          mkdir -p $(Build.BinariesDirectory)/version
          echo $(Build.BuildNumber) > $(Build.BinariesDirectory)/version/version.txt
    #- task: Bash@3
    #  displayName: 'Debug task only, check locations'
    #  inputs:
    #    targetType: 'inline'
    #    script: |
    #      # Figure out layout of the VM. 
    #      echo pwd:
    #      pwd
    #      echo
    #      ls
    #      echo $(Pipeline.Workspace)
    #      ls $(Pipeline.Workspace)
    # Note that VSCode may show an intellisense errors for some tasks:
    #    String does not match the pattern of "^PowerShell@2$"
    # This seems to be a bug in VSCode or a plugin. Ignore.
    - task: CopyFiles@2
      displayName: 'Copy build output to the artifact staging directory'
      inputs:
        sourceFolder: '$(root_out_dir)'
        contents: |
              deb_pkgs/**
              py_pkgs/**
              r_pkgs/**
              *.*
        targetFolder: '$(Build.ArtifactStagingDirectory)/release'

    - task: CopyFiles@2
      displayName: Copy files for installer version
      inputs:
        sourceFolder: '$(Build.BinariesDirectory)/version'
        contents: '*.*'
        targetFolder: '$(Build.ArtifactStagingDirectory)/version'

    # Note that the MS azure doc seems to advocate using the PublishPipelineArtifact task.
    # However this was too abstract to me, without a useful examplar to start from
    # Instead, using UniversalPackages which worked out OK

    #- task: PublishPipelineArtifact@1
    #  inputs:
    #    targetPath: '$(Pipeline.Workspace)'
    #    artifact: 'WaaInstaller'
    #    publishLocation: 'pipeline'
    #- task: UniversalPackages@0
    #  displayName: Publish output bundle
    #  inputs:
    #    command: publish
    #    publishDirectory: '$(Build.ArtifactStagingDirectory)/release'
    #    vstsFeedPublish: 'OD222236-DigWaterAndLandscapes/hydro_forecast_deb'
    #    vstsFeedPackagePublish: 'swift_deb'
    #    versionOption: custom
    #    versionPublish: '$(Build.BuildNumber)'
    #    packagePublishDescription: 'Debian packages for swift and co.'
    #- task: UniversalPackages@0
    #  displayName: Publish output bundle version
    #  inputs:
    #    command: publish
    #    publishDirectory: '$(Build.ArtifactStagingDirectory)/version'
    #    vstsFeedPublish: 'OD222236-DigWaterAndLandscapes/hydro_forecast_deb'
    #    vstsFeedPackagePublish: 'swift_deb_version'
    #    versionOption: custom
    #    versionPublish: '$(Build.BuildNumber)'
    #    packagePublishDescription: 'Version number for Debian packages for swift and co. bundle'


