# FROM debian:bullseye-slim
# FROM debian:bullseye-20220711-slim

# March 25 I notice that the base of scipy-notebook has moved to be based on noble ubuntu 24.04
# docker pull ubuntu:noble-20250127
FROM ubuntu:noble-20250127 as ubuntu-noble-202501

LABEL au.csiro.image.authors="jean-michel.perraud@csiro.au"
LABEL maintainer="J-M <jean-michel.perraud@csiro.au>"
LABEL product="Ubuntu Jammy image used for CI pipeline for streamflow forecasting"
LABEL version="0.1"
# Tell the agent about Node.js
LABEL "com.azure.dev.pipelines.agent.handler.node.path"="/usr/bin/node"

USER root

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Australia/Canberra
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ARG CURRENT_UID_ARG
ENV CURRENT_UID=${CURRENT_UID_ARG}

# Azure devops pipelines uses nodejs. It may bring its own though, so not sure whether installing it here is a good idea or not. Maybe BYO is fine. Let's see.
# https://learn.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops

# readline-common and co, to sudo may be needed?: see https://learn.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops

RUN apt-get update --yes && \
  apt-get install --yes --no-install-recommends \
  git \
  git-lfs \
  ssh-client \
  cmake \
  catch \
  g++ \
  nano \
  p7zip-full \
  curl \
  nodejs \
  adduser \
  readline-common \
  sudo \
  libboost-system-dev \
  libboost-date-time-dev \
  libboost-regex-dev \
  libboost-filesystem-dev \
  libboost-graph-dev \
  libboost-thread-dev \
  libtbb-dev \
  libnetcdf-dev \
  libudunits2-dev \
  libeigen3-dev \
  libyaml-cpp-dev \
  libjsoncpp-dev \
  r-cran-rcpp \
  r-cran-knitr \
  r-cran-lubridate \
  r-cran-zoo \
  r-cran-xts \
  r-cran-ggplot2 \
  r-cran-plyr \
  r-cran-dplyr \
  r-cran-rmarkdown \
  r-cran-readr \
  r-cran-mvtnorm \
  r-cran-ncdf4 \
  r-cran-udunits2 \
  r-cran-igraph \
  r-cran-roxygen2 \
  r-cran-markdown \
  r-cran-stringr \
  r-cran-devtools \
  r-cran-readr \
  r-cran-tibble \
  r-cran-cpp11 \
  r-cran-rlang \
  r-cran-tidyselect \
  r-cran-lifecycle \
  r-cran-pillar \
  r-cran-viridis \
  r-cran-viridislite \
  r-cran-gridextra \
  r-cran-downloader \
  r-cran-htmltools \
  r-cran-glue \
  pandoc \
  python3 \
  python3-venv\
  python3-pip \
  dh-make  \
  equivs \
  devscripts \
  build-essential \
  dh-cmake 
  
  # pandoc-citeproc is not on noble anymore. May impact R vignettes if I recall. 
  # https://forum.posit.co/t/github-action-e-package-pandoc-citeproc-has-no-installation-candidate/197536
  # pandoc-citeproc \


# Ubuntu packaging seems to require some of these explicitely: 
RUN apt-get install -y \
  libtbb2 \
  libnetcdf19 \
  libyaml-cpp0.7 \
  libyaml-0-2 


RUN apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /baseimage

COPY setup_dependent_packages.r /baseimage
COPY setup-deps.sh /baseimage

RUN ./setup-deps.sh

# following CMD infered from an example. May or may be not required
# https://learn.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops#full-example-of-a-dockerfile
CMD [ "node" ]